### ISSUE TITLE
图片生成失败 'Version' object has no attribute 'predict'

### ISSUE THREAD

**Issue by sephrioth** [lanvent/plugin_replicate#7]
模型都报同一个错误 
`HTTP Request: GET https://api.replicate.com/v1/models/luosiallen/latent-consistency-model "HTTP/1.1 200 OK"
HTTP Request: GET https://api.replicate.com/v1/models/luosiallen/latent-consistency-model/versions/553803fd018b3cf875a8bc774c99da9b33f36647badfd88a6eec90d61c5f62fc "HTTP/1.1 200 OK"
[ERROR][2023-11-13 21:30:46][main.py:159] - [RP] exception: 'Version' object has no attribute 'predict'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechatcom/plugins/plugin_replicate/main.py", line 125, in on_handle_context
    result = version.predict(**params)
AttributeError: 'Version' object has no attribute 'predict'`

**Comment by linqiu919** [comment]
Version.predict()方法貌似已经被弃用了，现在推荐使用replicate.run这个方法了。
[Update deprecation warnings for Model.predict and Version.predict #137
更新 Model.predict 和 Version.predict 的弃用警告 #137](https://github.com/replicate/replicate-python/pull/137/commits)

**Comment by sephrioth** [comment]
> Version.predict()方法貌似已经被弃用了，现在推荐使用replicate.run这个方法了。 [Update deprecation warnings for Model.predict and Version.predict #137 更新 Model.predict 和 Version.predict 的弃用警告 #137](https://github.com/replicate/replicate-python/pull/137/commits)

尝试改了下， 但是还是失败了...  好像作者也停止更新了

**Comment by linqiu919** [comment]
需要画图还是接入Link.AI用midjourney吧，这个即使可以使用效果也不是很好。

**Comment by sephrioth** [comment]
> 需要画图还是接入Link.AI用midjourney吧，这个即使可以使用效果也不是很好。

主要是这个可以很容易通过关键词来选择合适的模型...

**Comment by lanvent** [comment]
装<=0.10.0的replicate包可以用吗

**Comment by sephrioth** [comment]
> 装<=0.10.0的replicate包可以用吗

作者现身了！

还没有尝试过老的包， 等有空我我试试， 不过最好的方法还是支持新的方法吧

**Comment by linqiu919** [comment]
已测试，降级为0.10.0版本后可正常使用。

**Comment by lanvent** [comment]
感谢反馈，已限制replicate版本。根据官方的pr信息，应该只修改了api调用方法，对性能没有影响。等有空时候再适配一下新版本的api  :)

**Comment by sephrioth** [comment]
奇怪， 我降级为 0.10.0 后还是发生了报错

`[ERROR][2023-11-20 22:57:08][main.py:159] - [RP] exception: Invalid reference to model version: fofr/latent-consistency-model. Expected format: owner/name:version
Traceback (most recent call last):
  File "/root/chatgpt-on-wechatcom/plugins/plugin_replicate/main.py", line 125, in on_handle_context
    result = version.predict(**params)
  File "/usr/local/lib/python3.8/site-packages/replicate/client.py", line 141, in run
    ):
  File "/usr/local/lib/python3.8/site-packages/replicate/run.py", line 29, in run
replicate.exceptions.ReplicateError: Invalid reference to model version: fofr/latent-consistency-model. Expected format: owner/name:version`

**Comment by linqiu919** [comment]
卸载重装插件试

**Comment by markgeen** [comment]
> 模型都报同一个错误 `HTTP Request: GET https://api.replicate.com/v1/models/luosiallen/latent-consistency-model "HTTP/1.1 200 OK" HTTP Request: GET https://api.replicate.com/v1/models/luosiallen/latent-consistency-model/versions/553803fd018b3cf875a8bc774c99da9b33f36647badfd88a6eec90d61c5f62fc "HTTP/1.1 200 OK" [ERROR][2023-11-13 21:30:46][main.py:159] - [RP] exception: 'Version' object has no attribute 'predict' Traceback (most recent call last): File "/root/chatgpt-on-wechatcom/plugins/plugin_replicate/main.py", line 125, in on_handle_context result = version.predict(**params) AttributeError: 'Version' object has no attribute 'predict'`

感谢各位先遣者的提醒，我找到我的问题和你一样。but重新卸载安装真能没有了version的问题。不过图片并没有发出来，点开url一看是replicate网站的报错
![image](https://github.com/lanvent/plugin_replicate/assets/140533309/68c3421d-537f-4690-8b76-098891deac7f)。不过好像今晚我用replicate网站img2video也一直错误，可能是网站出问题了吗？
